-- ============================================================================
-- Employee Management API - SQL Script
-- Run this in MySQL Workbench. It covers Steps 2 and 13 of the assignment:
--   1. Database creation
--   2. Table creation (with keys/constraints)
--   3. Relationships
--   4. Sample data
--   5. Database management operations
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. DATABASE CREATION
-- ----------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS employee_management
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE employee_management;

-- ----------------------------------------------------------------------------
-- 2. TABLE CREATION
-- ----------------------------------------------------------------------------

DROP TABLE IF EXISTS employee_activity;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(120) NOT NULL,
    password      VARCHAR(255) NOT NULL,          -- stores a bcrypt HASH, never plain text
    role          ENUM('admin', 'manager', 'employee') NOT NULL DEFAULT 'employee',
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
) ENGINE=InnoDB;

CREATE TABLE employees (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(120) NOT NULL,
    department    VARCHAR(80)  NOT NULL,
    salary        DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    joining_date  DATE         NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_by    INT          NOT NULL,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT chk_employees_salary CHECK (salary >= 0),
    -- 3. RELATIONSHIP: each employee was created by exactly one user (admin/manager)
    CONSTRAINT fk_employees_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE employee_activity (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    employee_id    INT          NOT NULL,
    action         VARCHAR(50)  NOT NULL,
    details        VARCHAR(255),
    performed_by   INT          NOT NULL,
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_activity_performed_by
        FOREIGN KEY (performed_by) REFERENCES users(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX idx_employees_department ON employees(department);
CREATE INDEX idx_employees_name ON employees(name);
CREATE INDEX idx_employees_salary ON employees(salary);

-- ----------------------------------------------------------------------------
-- 4. SAMPLE DATA
-- Note: these password hashes are placeholders for illustration only.
-- Real hashes are generated by the API's /auth/register endpoint (bcrypt).
-- ----------------------------------------------------------------------------

INSERT INTO users (username, email, password, role, is_active) VALUES
('admin_raj',    'admin.raj@example.com',    '$2b$12$examplehashadmin000000000000000000000000000000000', 'admin',    TRUE),
('manager_priya','manager.priya@example.com','$2b$12$examplehashmanager0000000000000000000000000000000', 'manager',  TRUE),
('emp_siva',     'siva@example.com',         '$2b$12$examplehashemployee000000000000000000000000000000', 'employee', TRUE);

INSERT INTO employees (name, email, department, salary, joining_date, is_active, created_by) VALUES
('Siva Kumar',    'siva.kumar@example.com',    'IT',        65000.00, '2022-03-15', TRUE, 1),
('Ananya Rao',    'ananya.rao@example.com',    'IT',        72000.00, '2021-07-01', TRUE, 1),
('Rahul Mehta',   'rahul.mehta@example.com',   'Finance',   58000.00, '2023-01-10', TRUE, 2),
('Divya Nair',    'divya.nair@example.com',    'HR',        49000.00, '2020-11-20', TRUE, 2),
('Karthik Iyer',  'karthik.iyer@example.com',  'Finance',   81000.00, '2019-05-05', TRUE, 1),
('Meena Pillai',  'meena.pillai@example.com',  'Marketing', 54000.00, '2022-09-12', FALSE, 2);

-- ----------------------------------------------------------------------------
-- 5. DATABASE MANAGEMENT OPERATIONS
-- ----------------------------------------------------------------------------

-- Update employee salary
UPDATE employees SET salary = 70000.00 WHERE email = 'siva.kumar@example.com';

-- Update employee department
UPDATE employees SET department = 'Operations' WHERE email = 'rahul.mehta@example.com';

-- Find employees with salary greater than a specified amount
SELECT * FROM employees WHERE salary > 60000 AND is_active = TRUE;

-- Find the highest-paid employee
SELECT * FROM employees
WHERE is_active = TRUE
ORDER BY salary DESC
LIMIT 1;

-- Find the average salary
SELECT AVG(salary) AS average_salary FROM employees WHERE is_active = TRUE;

-- Count employees by department
SELECT department, COUNT(*) AS employee_count
FROM employees
WHERE is_active = TRUE
GROUP BY department
ORDER BY employee_count DESC;

-- Retrieve employees using SQL JOIN (employee + the user who created them)
SELECT
    e.id,
    e.name,
    e.department,
    e.salary,
    u.username AS created_by_username,
    u.role AS created_by_role
FROM employees e
JOIN users u ON e.created_by = u.id
ORDER BY e.id;

-- Identify duplicate employee emails (should return none, since email is UNIQUE;
-- this query is useful before the constraint is added, or on imported data)
SELECT email, COUNT(*) AS occurrences
FROM employees
GROUP BY email
HAVING COUNT(*) > 1;

-- Deactivate a record (soft delete, mirrors what the API's DELETE endpoint does)
UPDATE employees SET is_active = FALSE WHERE email = 'karthik.iyer@example.com';

-- Permanently delete a record (only for cleanup/testing; the API itself never hard-deletes)
-- DELETE FROM employees WHERE email = 'someone.to.remove@example.com';
